apiVersion: v1
kind: Service
metadata:
  name: assignment-1
  namespace: default
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
