name: my first workflow
on: push

jobs: 
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: welcome message
          run: echo "my name is waqas ahmad"

        - name: list files
          run: ls
