name: my first workflow
on: push

jobs: 
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: checkout actions
          uses: actions/checkout@v4
        - name: welcome message
          run: |
            echo "my name is waqas ahmad"
            ls
            cat README.md

        
