name: my first workflow
on: push

jobs: 
    first_jobs:
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout actions
          uses: actions/checkout@v4

        - name: Install cowsay
          run: |
           sudo apt-get install cowsay -y
           cowsay -f dragon "Hi i am a dragon leave me alone" >> dragon.txt

        
    second_job:
        runs-on: ubuntu-latest
        needs: first_jobs

        steps:
        - name: checkout actions
          uses: actions/checkout@v4

        - name: print 
          run: cat dragon.txt

    third_job:
        runs-on: ubuntu-latest
        needs: second_job
        steps:
        - name: checkout actions
          uses: actions/checkout@v4

        - name: list the job
          run: ls -la

